//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opalenica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opalenica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_AcceptButton {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_ApplyButton {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_CancelButton {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen On Start.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_FullScreenLabel {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.FullScreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_LanguageLabel {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_ModeLabel {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Monitor.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_MonitorLabel {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.MonitorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Restart the application for the changes to take effect.
        /// </summary>
        internal static string Forms_Settings_GeneralSettingsControl_RestartInfoLabel {
            get {
                return ResourceManager.GetString("Forms.Settings.GeneralSettingsControl.RestartInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block System.
        /// </summary>
        internal static string Settings_Tabs_BlockSys {
            get {
                return ResourceManager.GetString("Settings.Tabs.BlockSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_Tabs_General {
            get {
                return ResourceManager.GetString("Settings.Tabs.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junctions.
        /// </summary>
        internal static string Settings_Tabs_Junctions {
            get {
                return ResourceManager.GetString("Settings.Tabs.Junctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Settings_Tabs_SerialPort {
            get {
                return ResourceManager.GetString("Settings.Tabs.SerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals.
        /// </summary>
        internal static string Settings_Tabs_Signals {
            get {
                return ResourceManager.GetString("Settings.Tabs.Signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string Settings_Tabs_Tracks {
            get {
                return ResourceManager.GetString("Settings.Tabs.Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opalenica.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
